declare namespace CodeClimbers {
  export interface Pulse {
    id?: number
    userId: string // Used by wakatime to identify the user (email address).  We store as "local"
    entity: string // The activity that was done. The file worked on or the url of the site visited
    type: string // What type of entity it is.  For example: 'file' or 'domain'
    category?: string // What category the activity falls under.  For example: 'coding', 'browsing', 'designing'
    project?: string // The project the activity was done under. Gathered from the directory name the work was done from. Only used for 'file' type activities
    branch?: string // The branch the activity was done under. Gathered from the git branch the work was done from. Only used for 'file' type activities
    language?: string // The language the activity was done in. Gathered from the file extension. Only used for 'file' type activities
    isWrite: boolean // Whether the activity was a write operation.  If false, it was a read operation
    editor: string // if the activity was done in an editor, the name of the editor.  Only used for 'file' type activities
    operatingSystem: string // The operating system the activity was done on.  Gathered from the user agent
    application?: string // The application the activity was done in.
    machine: string // The machine the activity was done on.  Gathered from the user agent
    userAgent: string // The user agent of the activity.  Used to determine the operating system and application
    time: string // The time the activity was done.  In ISO format
    hash: string // A hash of the activity.  Used to determine if the activity is a duplicate. Browser extension sends a lot of duplicate activities
    origin?: string // unused
    originId?: string // unused
    createdAt: string // The time the activity was created in the database.  In ISO format
    description?: string // A description of the activity generated by the cli based on the other fields
  }
}
