name: Bump Minor Version

on:
  workflow_dispatch:

jobs:
  bump_minor_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Bump version
        run: |
          git checkout main
          npm version minor

      - name: Push changes
        run: |
          git branch --all
          git push origin main
          git push --tags
