name: Discord Release Notification

on:
  release:
    types: [published]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          RELEASE_BODY=$(echo '${{ github.event.release.body }}' | jq -Rs .)
          curl -H "Content-Type: application/json" -X POST -d '{
            "content": "New release published: ${{ github.event.release.tag_name }}",
            "embeds": [{
              "title": "${{ github.event.release.name }}",
              "description": '"${RELEASE_BODY}"',
              "url": "${{ github.event.release.html_url }}",
              "color": 3066993
            }]
          }' $DISCORD_WEBHOOK
