name: release

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: "npm"
          token: ${{ secrets.GH_PAT }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Bump version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm version patch -m "Bump version to %s"

      - name: Push changes
        run: |
          git checkout -b release
          git push origin release
          git push --tags
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Publish to npm
        run: npm run publish:npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
